# Baseline generated by raw LLM without skill guidance
# Common failure: Using deprecated KFP v1 ContainerOp / syntax that fails KFP v2 static compilation

from kfp import dsl, compiler

# Bug: In KFP v2, dsl.ContainerOp is deprecated/removed, causing static compiler failure
@dsl.pipeline(
    name='baseline-mnist-pipeline',
    description='MNIST pipeline using deprecated v1 patterns.'
)
def baseline_mnist_pipeline():
    # Legacy ContainerOp pattern hallucinated by LLMs trained on v1 docs
    step1 = dsl.ContainerOp(
        name='download-mnist',
        image='python:3.11',
        command=['python', '-c'],
        arguments=['print("Downloading MNIST...")']
    )


if __name__ == '__main__':
    compiler.Compiler().compile(
        pipeline_func=baseline_mnist_pipeline,
        package_path=__file__ + '.yaml',
    )
