# Baseline generated by raw LLM without skill guidance
# Common failure: Top-level imports outside component scope and missing packages_to_install

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

from kfp import compiler, dsl


@dsl.component
def download_iris(dataset_path: dsl.OutputPath(str)):
    """Downloads iris dataset."""
    # Bug: load_iris and pd are imported at top-level; in a fresh KFP pod this fails with NameError/ModuleNotFoundError
    iris = load_iris(as_frame=True)
    df = iris.frame
    df.to_csv(dataset_path, index=False)


@dsl.component
def train_and_eval(dataset_path: dsl.InputPath(str)) -> float:
    """Trains a logistic regression model."""
    df = pd.read_csv(dataset_path)
    X = df.drop(columns=['target'])
    y = df['target']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    clf = LogisticRegression(max_iter=200)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    acc = float(accuracy_score(y_test, y_pred))
    return acc


@dsl.pipeline(name='baseline-iris-pipeline')
def baseline_iris_pipeline():
    task1 = download_iris()
    task2 = train_and_eval(dataset_path=task1.outputs['dataset_path'])


if __name__ == '__main__':
    compiler.Compiler().compile(
        pipeline_func=baseline_iris_pipeline,
        package_path=__file__ + '.yaml',
    )
