# Baseline generated by raw LLM without skill guidance
# Common failure: Missing vision dependencies (pillow, opencv) and unhandled directory structures

from kfp import compiler, dsl


@dsl.component
# Bug: Missing packages_to_install=['Pillow', 'numpy']
def fetch_image_batch(output_dir: dsl.OutputPath(str)):
    import os
    import numpy as np
    from PIL import Image

    os.makedirs(output_dir, exist_ok=True)
    # Generate dummy image
    img = Image.fromarray(np.uint8(np.random.rand(100, 100, 3) * 255))
    img.save(os.path.join(output_dir, 'sample.png'))


@dsl.component
def train_anomaly_detector(input_dir: dsl.InputPath(str)) -> float:
    # Bug: Missing packages_to_install=['scikit-learn']
    from sklearn.ensemble import IsolationForest
    import numpy as np
    import os

    clf = IsolationForest()
    # Dummy fit
    clf.fit(np.random.randn(10, 5))
    return 0.95


@dsl.pipeline(name='baseline-image-anomaly-pipeline')
def baseline_image_anomaly_pipeline():
    s1 = fetch_image_batch()
    s2 = train_anomaly_detector(input_dir=s1.outputs['output_dir'])


if __name__ == '__main__':
    compiler.Compiler().compile(
        pipeline_func=baseline_image_anomaly_pipeline,
        package_path=__file__ + '.yaml',
    )
