# Baseline generated by raw LLM without skill guidance
# Common failure: Non-serializable numpy metric logging and missing typed Output[Metrics] artifacts

from kfp import compiler, dsl


@dsl.component(packages_to_install=['numpy', 'pandas', 'scikit-learn'])
def extract_telemetry(data_path: dsl.OutputPath(str)):
    import numpy as np
    import pandas as pd

    data = np.random.randn(100, 5)
    df = pd.DataFrame(data, columns=[f'f{i}' for i in range(5)])
    df.to_csv(data_path, index=False)


@dsl.component(packages_to_install=['pandas', 'scikit-learn', 'numpy'])
def train_and_eval(data_path: dsl.InputPath(str), metrics: dsl.Output[dsl.Metrics]):
    import numpy as np
    import pandas as pd
    from sklearn.linear_model import Ridge

    df = pd.read_csv(data_path)
    X = df.iloc[:, :-1]
    y = df.iloc[:, -1]
    model = Ridge().fit(X, y)
    
    # Bug: Passing numpy.float64 directly into log_metric instead of native python float,
    # or failing proto serialization
    mae = np.mean(np.abs(model.predict(X) - y))
    # Native KFP v2 requires float(mae), raw LLMs often pass raw np.float64 or dict
    metrics.log_metric('mae', mae)


@dsl.pipeline(name='baseline-time-series-pipeline')
def baseline_time_series_pipeline():
    s1 = extract_telemetry()
    s2 = train_and_eval(data_path=s1.outputs['data_path'])


if __name__ == '__main__':
    compiler.Compiler().compile(
        pipeline_func=baseline_time_series_pipeline,
        package_path=__file__ + '.yaml',
    )
